// <auto-generated />
using System;
using Bansang.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bansang.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260926085132_AddSales")]
    partial class AddSales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bansang.Domain.Catalog.PriceRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("MinQty")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("min_qty");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tier");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unit_name");

                    b.HasKey("Id")
                        .HasName("pk_price_rule");

                    b.HasIndex("SkuId", "UnitName", "Tier", "MinQty")
                        .IsUnique()
                        .HasDatabaseName("ix_price_rule_sku_id_unit_name_tier_min_qty");

                    b.ToTable("price_rule", (string)null);
                });

            modelBuilder.Entity("Bansang.Domain.Catalog.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_products_name");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Bansang.Domain.Catalog.Sku", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AvgCostPerBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("avg_cost_per_base");

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("base_unit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Spec")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("spec");

                    b.Property<string>("TrackingPattern")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tracking_pattern");

                    b.HasKey("Id")
                        .HasName("pk_skus");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_skus_code");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_skus_product_id");

                    b.ToTable("skus", (string)null);
                });

            modelBuilder.Entity("Bansang.Domain.Catalog.SkuUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("barcode");

                    b.Property<bool>("CanBuy")
                        .HasColumnType("boolean")
                        .HasColumnName("can_buy");

                    b.Property<bool>("CanSell")
                        .HasColumnType("boolean")
                        .HasColumnName("can_sell");

                    b.Property<decimal>("FactorToBase")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("factor_to_base");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("form");

                    b.Property<bool>("IsBase")
                        .HasColumnType("boolean")
                        .HasColumnName("is_base");

                    b.Property<bool>("IsExact")
                        .HasColumnType("boolean")
                        .HasColumnName("is_exact");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unit_name");

                    b.HasKey("Id")
                        .HasName("pk_sku_units");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasDatabaseName("ix_sku_units_barcode")
                        .HasFilter("barcode IS NOT NULL");

                    b.HasIndex("SkuId", "UnitName")
                        .IsUnique()
                        .HasDatabaseName("ix_sku_units_sku_id_unit_name");

                    b.ToTable("sku_units", (string)null);
                });

            modelBuilder.Entity("Bansang.Domain.Inventory.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_locations_code");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("Bansang.Domain.Inventory.StockBucket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("form");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<bool>("NeedsCount")
                        .HasColumnType("boolean")
                        .HasColumnName("needs_count");

                    b.Property<decimal>("QtyOnHandBase")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("qty_on_hand_base");

                    b.Property<decimal>("QtyReservedBase")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("qty_reserved_base");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.HasKey("Id")
                        .HasName("pk_stock_buckets");

                    b.HasIndex("LocationId", "NeedsCount")
                        .HasDatabaseName("ix_stock_buckets_location_id_needs_count");

                    b.HasIndex("SkuId", "LocationId", "Form")
                        .IsUnique()
                        .HasDatabaseName("ix_stock_buckets_sku_id_location_id_form");

                    b.ToTable("stock_buckets", (string)null);
                });

            modelBuilder.Entity("Bansang.Domain.Inventory.StockCount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<decimal>("ThresholdPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("threshold_percent");

                    b.HasKey("Id")
                        .HasName("pk_stock_counts");

                    b.HasIndex("LocationId", "CreatedAt")
                        .HasDatabaseName("ix_stock_counts_location_id_created_at");

                    b.ToTable("stock_counts", (string)null);
                });

            modelBuilder.Entity("Bansang.Domain.Inventory.StockCountLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AdjustmentMovementId")
                        .HasColumnType("uuid")
                        .HasColumnName("adjustment_movement_id");

                    b.Property<Guid>("CountId")
                        .HasColumnType("uuid")
                        .HasColumnName("count_id");

                    b.Property<DateTimeOffset>("CountedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("counted_at");

                    b.Property<string>("CountedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("counted_by");

                    b.Property<decimal?>("CountedInputQty")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("counted_input_qty");

                    b.Property<decimal>("CountedQtyBase")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("counted_qty_base");

                    b.Property<string>("CountedUnit")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("counted_unit");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("form");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resolved_by");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<decimal>("SystemQtyBase")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("system_qty_base");

                    b.Property<decimal>("VarianceBase")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("variance_base");

                    b.Property<decimal>("VariancePercent")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)")
                        .HasColumnName("variance_percent");

                    b.HasKey("Id")
                        .HasName("pk_stock_count_lines");

                    b.HasIndex("CountId")
                        .HasDatabaseName("ix_stock_count_lines_count_id");

                    b.HasIndex("SkuId", "CountedAt")
                        .HasDatabaseName("ix_stock_count_lines_sku_id_counted_at");

                    b.ToTable("stock_count_lines", (string)null);
                });

            modelBuilder.Entity("Bansang.Domain.Inventory.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<decimal>("BalanceAfterBase")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("balance_after_base");

                    b.Property<Guid>("BucketId")
                        .HasColumnType("uuid")
                        .HasColumnName("bucket_id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<decimal>("CostPerBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("cost_per_base");

                    b.Property<decimal?>("FactorSnapshot")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("factor_snapshot");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("form");

                    b.Property<decimal?>("InputQty")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("input_qty");

                    b.Property<string>("InputUnit")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("input_unit");

                    b.Property<bool>("IsApproximate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_approximate");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<decimal>("QtyBase")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("qty_base");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("RefDocument")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ref_document");

                    b.Property<Guid?>("ReversalOfId")
                        .HasColumnType("uuid")
                        .HasColumnName("reversal_of_id");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_stock_movements");

                    b.HasIndex("BucketId")
                        .HasDatabaseName("ix_stock_movements_bucket_id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_stock_movements_correlation_id");

                    b.HasIndex("RefDocument")
                        .HasDatabaseName("ix_stock_movements_ref_document");

                    b.HasIndex("ReversalOfId")
                        .IsUnique()
                        .HasDatabaseName("ix_stock_movements_reversal_of_id")
                        .HasFilter("reversal_of_id IS NOT NULL");

                    b.HasIndex("SkuId", "At")
                        .HasDatabaseName("ix_stock_movements_sku_id_at");

                    b.ToTable("stock_movements", (string)null);
                });

            modelBuilder.Entity("Bansang.Domain.Sales.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("TaxId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tax_id");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tier");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_code");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_customers_name");

                    b.HasIndex("Phone")
                        .HasDatabaseName("ix_customers_phone");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Bansang.Domain.Sales.Fulfillment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("number");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_fulfillment");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_fulfillment_number");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_fulfillment_order_id");

                    b.ToTable("fulfillment", (string)null);
                });

            modelBuilder.Entity("Bansang.Domain.Sales.FulfillmentLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FulfillmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("fulfillment_id");

                    b.Property<decimal>("Qty")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("qty");

                    b.Property<decimal>("QtyBase")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("qty_base");

                    b.Property<Guid>("SalesLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_line_id");

                    b.HasKey("Id")
                        .HasName("pk_fulfillment_line");

                    b.HasIndex("FulfillmentId")
                        .HasDatabaseName("ix_fulfillment_line_fulfillment_id");

                    b.HasIndex("SalesLineId")
                        .HasDatabaseName("ix_fulfillment_line_sales_line_id");

                    b.ToTable("fulfillment_line", (string)null);
                });

            modelBuilder.Entity("Bansang.Domain.Sales.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<bool>("IsRefund")
                        .HasColumnType("boolean")
                        .HasColumnName("is_refund");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("method");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference");

                    b.Property<Guid?>("ReturnId")
                        .HasColumnType("uuid")
                        .HasColumnName("return_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_payment");

                    b.HasIndex("At")
                        .HasDatabaseName("ix_payment_at");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_payment_order_id");

                    b.ToTable("payment", (string)null);
                });

            modelBuilder.Entity("Bansang.Domain.Sales.Quotation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BillDiscount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("bill_discount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("number");

                    b.Property<Guid?>("SalesOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_order_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tier");

                    b.Property<DateOnly>("ValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("valid_until");

                    b.Property<decimal>("VatRatePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("vat_rate_percent");

                    b.HasKey("Id")
                        .HasName("pk_quotations");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_quotations_customer_id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_quotations_number");

                    b.ToTable("quotations", (string)null);
                });

            modelBuilder.Entity("Bansang.Domain.Sales.QuotationLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<decimal>("LineDiscount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("line_discount");

                    b.Property<int>("LineNo")
                        .HasColumnType("integer")
                        .HasColumnName("line_no");

                    b.Property<decimal>("Qty")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("qty");

                    b.Property<Guid>("QuotationId")
                        .HasColumnType("uuid")
                        .HasColumnName("quotation_id");

                    b.Property<string>("SkuCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku_code");

                    b.Property<Guid?>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unit_name");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_quotation_line");

                    b.HasIndex("QuotationId")
                        .HasDatabaseName("ix_quotation_line_quotation_id");

                    b.HasIndex("SkuId")
                        .HasDatabaseName("ix_quotation_line_sku_id");

                    b.ToTable("quotation_line", (string)null);
                });

            modelBuilder.Entity("Bansang.Domain.Sales.SalesLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<decimal?>("FactorSnapshot")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("factor_snapshot");

                    b.Property<string>("Form")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("form");

                    b.Property<decimal>("FulfilledBase")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("fulfilled_base");

                    b.Property<decimal>("FulfilledQty")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("fulfilled_qty");

                    b.Property<bool>("IsApproximate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_approximate");

                    b.Property<decimal>("LineDiscount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("line_discount");

                    b.Property<int>("LineNo")
                        .HasColumnType("integer")
                        .HasColumnName("line_no");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("PriceSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("price_source");

                    b.Property<decimal>("Qty")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("qty");

                    b.Property<decimal>("QtyBase")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("qty_base");

                    b.Property<decimal>("RefundedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("refunded_amount");

                    b.Property<decimal>("ReturnedBase")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("returned_base");

                    b.Property<decimal>("ReturnedQty")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("returned_qty");

                    b.Property<string>("SkuCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku_code");

                    b.Property<Guid?>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<bool>("TracksStock")
                        .HasColumnType("boolean")
                        .HasColumnName("tracks_stock");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unit_name");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_sales_line");

                    b.HasIndex("SkuId")
                        .HasDatabaseName("ix_sales_line_sku_id");

                    b.HasIndex("OrderId", "LineNo")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_line_order_id_line_no");

                    b.ToTable("sales_line", (string)null);
                });

            modelBuilder.Entity("Bansang.Domain.Sales.SalesOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BillDiscount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("bill_discount");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancel_reason");

                    b.Property<decimal>("ChangeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("change_amount");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<string>("ConfirmedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("confirmed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("mode");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<string>("Number")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("number");

                    b.Property<Guid?>("QuotationId")
                        .HasColumnType("uuid")
                        .HasColumnName("quotation_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tier");

                    b.Property<decimal>("VatRatePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("vat_rate_percent");

                    b.HasKey("Id")
                        .HasName("pk_sales_orders");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_sales_orders_customer_id");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_sales_orders_location_id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_orders_number")
                        .HasFilter("number IS NOT NULL");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_sales_orders_status_created_at");

                    b.ToTable("sales_orders", (string)null);
                });

            modelBuilder.Entity("Bansang.Domain.Sales.SalesReturn", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("number");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<decimal>("RefundAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("refund_amount");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sales_return");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_return_number");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_sales_return_order_id");

                    b.ToTable("sales_return", (string)null);
                });

            modelBuilder.Entity("Bansang.Domain.Sales.SalesReturnLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<decimal>("Qty")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("qty");

                    b.Property<decimal>("QtyBase")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("qty_base");

                    b.Property<Guid>("ReturnId")
                        .HasColumnType("uuid")
                        .HasColumnName("return_id");

                    b.Property<Guid>("SalesLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("sales_line_id");

                    b.HasKey("Id")
                        .HasName("pk_sales_return_line");

                    b.HasIndex("ReturnId")
                        .HasDatabaseName("ix_sales_return_line_return_id");

                    b.HasIndex("SalesLineId")
                        .HasDatabaseName("ix_sales_return_line_sales_line_id");

                    b.ToTable("sales_return_line", (string)null);
                });

            modelBuilder.Entity("Bansang.Infrastructure.Persistence.DocumentSequence", b =>
                {
                    b.Property<string>("Prefix")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("prefix");

                    b.Property<string>("Period")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("period");

                    b.Property<long>("LastValue")
                        .HasColumnType("bigint")
                        .HasColumnName("last_value");

                    b.HasKey("Prefix", "Period")
                        .HasName("pk_document_sequences");

                    b.ToTable("document_sequences", (string)null);
                });

            modelBuilder.Entity("Bansang.Domain.Catalog.PriceRule", b =>
                {
                    b.HasOne("Bansang.Domain.Catalog.Sku", null)
                        .WithMany("PriceRules")
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_price_rule_skus_sku_id");
                });

            modelBuilder.Entity("Bansang.Domain.Catalog.Sku", b =>
                {
                    b.HasOne("Bansang.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_skus_products_product_id");
                });

            modelBuilder.Entity("Bansang.Domain.Catalog.SkuUnit", b =>
                {
                    b.HasOne("Bansang.Domain.Catalog.Sku", null)
                        .WithMany("Units")
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sku_units_skus_sku_id");
                });

            modelBuilder.Entity("Bansang.Domain.Inventory.StockBucket", b =>
                {
                    b.HasOne("Bansang.Domain.Inventory.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_buckets_locations_location_id");

                    b.HasOne("Bansang.Domain.Catalog.Sku", null)
                        .WithMany()
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_buckets_skus_sku_id");
                });

            modelBuilder.Entity("Bansang.Domain.Inventory.StockCount", b =>
                {
                    b.HasOne("Bansang.Domain.Inventory.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_counts_locations_location_id");
                });

            modelBuilder.Entity("Bansang.Domain.Inventory.StockCountLine", b =>
                {
                    b.HasOne("Bansang.Domain.Inventory.StockCount", null)
                        .WithMany("Lines")
                        .HasForeignKey("CountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stock_count_lines_stock_counts_count_id");

                    b.HasOne("Bansang.Domain.Catalog.Sku", null)
                        .WithMany()
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_count_lines_skus_sku_id");
                });

            modelBuilder.Entity("Bansang.Domain.Inventory.StockMovement", b =>
                {
                    b.HasOne("Bansang.Domain.Inventory.StockBucket", null)
                        .WithMany()
                        .HasForeignKey("BucketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_movements_stock_buckets_bucket_id");
                });

            modelBuilder.Entity("Bansang.Domain.Sales.Fulfillment", b =>
                {
                    b.HasOne("Bansang.Domain.Sales.SalesOrder", null)
                        .WithMany("Fulfillments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fulfillment_sales_orders_order_id");
                });

            modelBuilder.Entity("Bansang.Domain.Sales.FulfillmentLine", b =>
                {
                    b.HasOne("Bansang.Domain.Sales.Fulfillment", null)
                        .WithMany("Lines")
                        .HasForeignKey("FulfillmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fulfillment_line_fulfillment_fulfillment_id");

                    b.HasOne("Bansang.Domain.Sales.SalesLine", null)
                        .WithMany()
                        .HasForeignKey("SalesLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fulfillment_line_sales_line_sales_line_id");
                });

            modelBuilder.Entity("Bansang.Domain.Sales.Payment", b =>
                {
                    b.HasOne("Bansang.Domain.Sales.SalesOrder", null)
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payment_sales_orders_order_id");
                });

            modelBuilder.Entity("Bansang.Domain.Sales.Quotation", b =>
                {
                    b.HasOne("Bansang.Domain.Sales.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_quotations_customers_customer_id");
                });

            modelBuilder.Entity("Bansang.Domain.Sales.QuotationLine", b =>
                {
                    b.HasOne("Bansang.Domain.Sales.Quotation", null)
                        .WithMany("Lines")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quotation_line_quotations_quotation_id");

                    b.HasOne("Bansang.Domain.Catalog.Sku", null)
                        .WithMany()
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_quotation_line_skus_sku_id");
                });

            modelBuilder.Entity("Bansang.Domain.Sales.SalesLine", b =>
                {
                    b.HasOne("Bansang.Domain.Sales.SalesOrder", null)
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_line_sales_orders_order_id");

                    b.HasOne("Bansang.Domain.Catalog.Sku", null)
                        .WithMany()
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sales_line_skus_sku_id");
                });

            modelBuilder.Entity("Bansang.Domain.Sales.SalesOrder", b =>
                {
                    b.HasOne("Bansang.Domain.Sales.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sales_orders_customers_customer_id");

                    b.HasOne("Bansang.Domain.Inventory.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_orders_locations_location_id");
                });

            modelBuilder.Entity("Bansang.Domain.Sales.SalesReturn", b =>
                {
                    b.HasOne("Bansang.Domain.Sales.SalesOrder", null)
                        .WithMany("Returns")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_return_sales_orders_order_id");
                });

            modelBuilder.Entity("Bansang.Domain.Sales.SalesReturnLine", b =>
                {
                    b.HasOne("Bansang.Domain.Sales.SalesReturn", null)
                        .WithMany("Lines")
                        .HasForeignKey("ReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_return_line_sales_return_return_id");

                    b.HasOne("Bansang.Domain.Sales.SalesLine", null)
                        .WithMany()
                        .HasForeignKey("SalesLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sales_return_line_sales_line_sales_line_id");
                });

            modelBuilder.Entity("Bansang.Domain.Catalog.Sku", b =>
                {
                    b.Navigation("PriceRules");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("Bansang.Domain.Inventory.StockCount", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Bansang.Domain.Sales.Fulfillment", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Bansang.Domain.Sales.Quotation", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Bansang.Domain.Sales.SalesOrder", b =>
                {
                    b.Navigation("Fulfillments");

                    b.Navigation("Lines");

                    b.Navigation("Payments");

                    b.Navigation("Returns");
                });

            modelBuilder.Entity("Bansang.Domain.Sales.SalesReturn", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
