// <auto-generated />
using System;
using Bansang.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bansang.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bansang.Domain.Catalog.PriceRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("MinQty")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("min_qty");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tier");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unit_name");

                    b.HasKey("Id")
                        .HasName("pk_price_rule");

                    b.HasIndex("SkuId", "UnitName", "Tier", "MinQty")
                        .IsUnique()
                        .HasDatabaseName("ix_price_rule_sku_id_unit_name_tier_min_qty");

                    b.ToTable("price_rule", (string)null);
                });

            modelBuilder.Entity("Bansang.Domain.Catalog.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_products_name");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Bansang.Domain.Catalog.Sku", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AvgCostPerBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("avg_cost_per_base");

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("base_unit");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Spec")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("spec");

                    b.Property<string>("TrackingPattern")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tracking_pattern");

                    b.HasKey("Id")
                        .HasName("pk_skus");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_skus_code");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_skus_product_id");

                    b.ToTable("skus", (string)null);
                });

            modelBuilder.Entity("Bansang.Domain.Catalog.SkuUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("barcode");

                    b.Property<bool>("CanBuy")
                        .HasColumnType("boolean")
                        .HasColumnName("can_buy");

                    b.Property<bool>("CanSell")
                        .HasColumnType("boolean")
                        .HasColumnName("can_sell");

                    b.Property<decimal>("FactorToBase")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("factor_to_base");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("form");

                    b.Property<bool>("IsBase")
                        .HasColumnType("boolean")
                        .HasColumnName("is_base");

                    b.Property<bool>("IsExact")
                        .HasColumnType("boolean")
                        .HasColumnName("is_exact");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("unit_name");

                    b.HasKey("Id")
                        .HasName("pk_sku_units");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasDatabaseName("ix_sku_units_barcode")
                        .HasFilter("barcode IS NOT NULL");

                    b.HasIndex("SkuId", "UnitName")
                        .IsUnique()
                        .HasDatabaseName("ix_sku_units_sku_id_unit_name");

                    b.ToTable("sku_units", (string)null);
                });

            modelBuilder.Entity("Bansang.Domain.Inventory.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_locations_code");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("Bansang.Domain.Inventory.StockBucket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("form");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<bool>("NeedsCount")
                        .HasColumnType("boolean")
                        .HasColumnName("needs_count");

                    b.Property<decimal>("QtyOnHandBase")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("qty_on_hand_base");

                    b.Property<decimal>("QtyReservedBase")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("qty_reserved_base");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.HasKey("Id")
                        .HasName("pk_stock_buckets");

                    b.HasIndex("LocationId", "NeedsCount")
                        .HasDatabaseName("ix_stock_buckets_location_id_needs_count");

                    b.HasIndex("SkuId", "LocationId", "Form")
                        .IsUnique()
                        .HasDatabaseName("ix_stock_buckets_sku_id_location_id_form");

                    b.ToTable("stock_buckets", (string)null);
                });

            modelBuilder.Entity("Bansang.Domain.Inventory.StockCount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<decimal>("ThresholdPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("threshold_percent");

                    b.HasKey("Id")
                        .HasName("pk_stock_counts");

                    b.HasIndex("LocationId", "CreatedAt")
                        .HasDatabaseName("ix_stock_counts_location_id_created_at");

                    b.ToTable("stock_counts", (string)null);
                });

            modelBuilder.Entity("Bansang.Domain.Inventory.StockCountLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AdjustmentMovementId")
                        .HasColumnType("uuid")
                        .HasColumnName("adjustment_movement_id");

                    b.Property<Guid>("CountId")
                        .HasColumnType("uuid")
                        .HasColumnName("count_id");

                    b.Property<DateTimeOffset>("CountedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("counted_at");

                    b.Property<string>("CountedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("counted_by");

                    b.Property<decimal?>("CountedInputQty")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("counted_input_qty");

                    b.Property<decimal>("CountedQtyBase")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("counted_qty_base");

                    b.Property<string>("CountedUnit")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("counted_unit");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("form");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resolved_by");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<decimal>("SystemQtyBase")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("system_qty_base");

                    b.Property<decimal>("VarianceBase")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("variance_base");

                    b.Property<decimal>("VariancePercent")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)")
                        .HasColumnName("variance_percent");

                    b.HasKey("Id")
                        .HasName("pk_stock_count_lines");

                    b.HasIndex("CountId")
                        .HasDatabaseName("ix_stock_count_lines_count_id");

                    b.HasIndex("SkuId", "CountedAt")
                        .HasDatabaseName("ix_stock_count_lines_sku_id_counted_at");

                    b.ToTable("stock_count_lines", (string)null);
                });

            modelBuilder.Entity("Bansang.Domain.Inventory.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<decimal>("BalanceAfterBase")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("balance_after_base");

                    b.Property<Guid>("BucketId")
                        .HasColumnType("uuid")
                        .HasColumnName("bucket_id");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<decimal>("CostPerBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("cost_per_base");

                    b.Property<decimal?>("FactorSnapshot")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("factor_snapshot");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("form");

                    b.Property<decimal?>("InputQty")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("input_qty");

                    b.Property<string>("InputUnit")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("input_unit");

                    b.Property<bool>("IsApproximate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_approximate");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<decimal>("QtyBase")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("qty_base");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("RefDocument")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ref_document");

                    b.Property<Guid?>("ReversalOfId")
                        .HasColumnType("uuid")
                        .HasColumnName("reversal_of_id");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("sku_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_stock_movements");

                    b.HasIndex("BucketId")
                        .HasDatabaseName("ix_stock_movements_bucket_id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_stock_movements_correlation_id");

                    b.HasIndex("RefDocument")
                        .HasDatabaseName("ix_stock_movements_ref_document");

                    b.HasIndex("ReversalOfId")
                        .IsUnique()
                        .HasDatabaseName("ix_stock_movements_reversal_of_id")
                        .HasFilter("reversal_of_id IS NOT NULL");

                    b.HasIndex("SkuId", "At")
                        .HasDatabaseName("ix_stock_movements_sku_id_at");

                    b.ToTable("stock_movements", (string)null);
                });

            modelBuilder.Entity("Bansang.Domain.Catalog.PriceRule", b =>
                {
                    b.HasOne("Bansang.Domain.Catalog.Sku", null)
                        .WithMany("PriceRules")
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_price_rule_skus_sku_id");
                });

            modelBuilder.Entity("Bansang.Domain.Catalog.Sku", b =>
                {
                    b.HasOne("Bansang.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_skus_products_product_id");
                });

            modelBuilder.Entity("Bansang.Domain.Catalog.SkuUnit", b =>
                {
                    b.HasOne("Bansang.Domain.Catalog.Sku", null)
                        .WithMany("Units")
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sku_units_skus_sku_id");
                });

            modelBuilder.Entity("Bansang.Domain.Inventory.StockBucket", b =>
                {
                    b.HasOne("Bansang.Domain.Inventory.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_buckets_locations_location_id");

                    b.HasOne("Bansang.Domain.Catalog.Sku", null)
                        .WithMany()
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_buckets_skus_sku_id");
                });

            modelBuilder.Entity("Bansang.Domain.Inventory.StockCount", b =>
                {
                    b.HasOne("Bansang.Domain.Inventory.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_counts_locations_location_id");
                });

            modelBuilder.Entity("Bansang.Domain.Inventory.StockCountLine", b =>
                {
                    b.HasOne("Bansang.Domain.Inventory.StockCount", null)
                        .WithMany("Lines")
                        .HasForeignKey("CountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stock_count_lines_stock_counts_count_id");

                    b.HasOne("Bansang.Domain.Catalog.Sku", null)
                        .WithMany()
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_count_lines_skus_sku_id");
                });

            modelBuilder.Entity("Bansang.Domain.Inventory.StockMovement", b =>
                {
                    b.HasOne("Bansang.Domain.Inventory.StockBucket", null)
                        .WithMany()
                        .HasForeignKey("BucketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_movements_stock_buckets_bucket_id");
                });

            modelBuilder.Entity("Bansang.Domain.Catalog.Sku", b =>
                {
                    b.Navigation("PriceRules");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("Bansang.Domain.Inventory.StockCount", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
